volumes:
  beta-data:
    external: true
services:
  web_client:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./Client//ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  database:
    image: postgres:14.2-bullseye
    volumes:
      - beta-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=inventory,sales,service
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  api:
    build:
      context: ./Backend/accounts/api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./service/poll:/app
      - ./service/api/service_project:/app/service_project
      - ./service/api/service_rest:/app/service_rest
    depends_on:
      - database
      - service-api
    environment:
      DATABASE_URL: postgres://service:password@database:5432/service
      WAIT_HOSTS: database:5432,service-api:8000
      WAIT_TIMEOUT: 240
  backend:
    build:
      context: ./Backend/accounts/api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./service/poll:/app
      - ./service/api/service_project:/app/service_project
      - ./service/api/service_rest:/app/service_rest
    depends_on:
      - database
      - service-api
    environment:
      DATABASE_URL: postgres://service:password@database:5432/service
      WAIT_HOSTS: database:5432,service-api:8000
      WAIT_TIMEOUT: 240
