volumes:
  postgres-data:
    external: true
  beta-data:
    external: true
  pg-admin:
    external: true
  kafka-data:
    external: true
  twilio-consumer:
    external: true
services:
  web_client:
    image: node:lts-bullseye
    command: npm run dev
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  database:
    image: postgres:14.5-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - beta-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - 15432:5432
  zookeeper:
    build:
      context: ./notifications
      dockerfile: Dockerfile.zookeeper
  kafka:
    build:
      context: ./notifications
      dockerfile: Dockerfile.kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  api:
    build:
      context: ./api
      dockerfile: .dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/db
      WAIT_HOSTS: database:5432,api:8000
      WAIT_TIMEOUT: 240
    ports:
      - "8000:8000"
